Integration with database
java-park-mail-ru/angry-birds-09-2016 pull request #2
Opened 2016-11-15 19:47 UTC by arid1995

2016-11-21 19:36 UTC, KSolovyev requested changes

2016-11-21 19:36 UTC, KSolovyev commented on src/main/java/ru/mail/park/database/HibernateUtils.java
> +public class HibernateUtils {
Давайте не будем использовать синглтон. Попробуйте подход спринга с его EntityManager'а http://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html. Или придумайте что-то свое, но на сервисах, управляемых спрингом

2016-11-21 19:36 UTC, KSolovyev commented on src/main/java/ru/mail/park/database/dao/UserDAO.java
> +        final Session session = HibernateUtils.getSessionFactory().openSession();
если используете сессию и транзакции, то надо использовать try-with-resources

2016-11-21 19:36 UTC, KSolovyev commented on src/main/java/ru/mail/park/database/entities/User.java
> +    private String email;
login и email надо сделать unique с помощью аннотации `@Column`

2016-11-21 19:36 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/game/GameController.java
> +public class GameController {
давайте уберем пока

2016-12-06 21:12 UTC, KSolovyev commented
Ребята, как дела?

2016-12-06 21:51 UTC, arid1995 commented
Были заняты базой данных. Завтра начнем работать

2016-12-15 21:05 UTC, KSolovyev commented
Стоп, стоп. Вам нужно сделать новую ветку от последнего коммита с БД, и прислать пул-реквест с нее. А то уже начала гейммеханика поподать в ченжлог

2016-12-15 21:05 UTC, closed without merging